In [1]:
import pandas as pd

In [7]:
# Loaded and inspected 2016

opioid_deaths_2016 = pd.read_csv(r"C:\Users\popov\Group1FinalProject\Milos\data\2016_Opioid_Overdoses_Wonder.xlsx - 2016.csv")
opioid_deaths_2016.head()

               County  County Code      Deaths Population  Crude Rate
0  Autauga County, AL       1001.0  Suppressed      55416  Suppressed
1  Baldwin County, AL       1003.0          18     208563  Unreliable
2  Barbour County, AL       1005.0  Suppressed      25965  Suppressed
3     Bibb County, AL       1007.0  Suppressed      22643  Suppressed
4   Blount County, AL       1009.0  Suppressed      57704  Suppressed

In [9]:
# Loaded and inspected 2017

opioid_deaths_2017 = pd.read_csv(r"C:\Users\popov\Group1FinalProject\Milos\data\2017_Opioid_Overdoses_Wonder.xlsx - 2017.csv")
opioid_deaths_2017.head()

               County  County Code      Deaths Population  Crude Rate
0  Autauga County, AL       1001.0  Suppressed      55504  Suppressed
1  Baldwin County, AL       1003.0          21     212628         9.9
2  Barbour County, AL       1005.0  Suppressed      25270  Suppressed
3     Bibb County, AL       1007.0  Suppressed      22668  Suppressed
4   Blount County, AL       1009.0  Suppressed      58013  Suppressed

In [10]:
# Loaded and inspected 2018

opioid_deaths_2018 = pd.read_csv(r"C:\Users\popov\Group1FinalProject\Milos\data\2018_Opioid_Overdoses_Wonder.xlsx - 2018.csv")
opioid_deaths_2018.head()

               County  County Code      Deaths Population  Crude Rate
0  Autauga County, AL       1001.0  Suppressed      55601  Suppressed
1  Baldwin County, AL       1003.0          14     218022  Unreliable
2  Barbour County, AL       1005.0  Suppressed      24881  Suppressed
3     Bibb County, AL       1007.0  Suppressed      22400  Suppressed
4   Blount County, AL       1009.0  Suppressed      57840  Suppressed

In [11]:
# Loaded and inspected 2019

opioid_deaths_2019 = pd.read_csv(r"C:\Users\popov\Group1FinalProject\Milos\data\2019_Opioid_Overdoses_Wonder.xlsx - 2019.csv")
opioid_deaths_2019.head()

               County  County Code      Deaths Population  Crude Rate
0  Autauga County, AL       1001.0  Suppressed      55869  Suppressed
1  Baldwin County, AL       1003.0          18     223234  Unreliable
2  Barbour County, AL       1005.0  Suppressed      24686  Suppressed
3     Bibb County, AL       1007.0  Suppressed      22394  Suppressed
4   Blount County, AL       1009.0  Suppressed      57826  Suppressed

In [13]:
# Loaded and inspected 2020

opioid_deaths_2020 = pd.read_csv(r"C:\Users\popov\Group1FinalProject\Milos\data\2020_Opioid_Overdoses_Wonder.xlsx - Sheet1.csv")
opioid_deaths_2020.head()

               County  County Code      Deaths Population  Crude Rate
0  Autauga County, AL       1001.0  Suppressed      56145  Suppressed
1  Baldwin County, AL       1003.0          41     229287        17.9
2  Barbour County, AL       1005.0  Suppressed      24589  Suppressed
3     Bibb County, AL       1007.0  Suppressed      22136  Suppressed
4   Blount County, AL       1009.0  Suppressed      57879  Suppressed

In [16]:
# Add a year column to each data frame
opioid_deaths_2016["Year"] = 2016
opioid_deaths_2017["Year"] = 2017
opioid_deaths_2018["Year"] = 2018
opioid_deaths_2019["Year"] = 2019
opioid_deaths_2020["Year"] = 2020

# Merge the data frames into one
opioid_deaths_all = pd.concat([opioid_deaths_2016, opioid_deaths_2017, opioid_deaths_2018, opioid_deaths_2019, opioid_deaths_2020], ignore_index=True)

# Print the first few rows of the merged data frame
opioid_deaths_all.tail()

,County,County Code,Deaths,Population,Crude Rate,Year
15735,"Teton County, WY",56039.0,Suppressed,23497,Suppressed,2020
15736,"Uinta County, WY",56041.0,Suppressed,20215,Suppressed,2020
15737,"Washakie County, WY",56043.0,Suppressed,7760,Suppressed,2020
15738,"Weston County, WY",56045.0,Suppressed,6743,Suppressed,2020
15739,NaN,NaN,70222,329474777,21.3,2020